# NOTE: This is the same as the root Dockerfile.
# For AWS deployments, build from the project root:
#   docker build -t flusk-observability .
#
# Or symlink:
#   ln -sf ../../Dockerfile deploy/aws/Dockerfile
